### ISSUE TITLE
_gyroRange question

### ISSUE THREAD

**Issue by qingyi-wang** [cdjq/DFRobot_ICM42688#1]
hello，I have some questions about the angle range of the gyroscope，here is :
 _gyroRange = 4000/65535.0;
The difference between my integrated value is half, it should be 90 degrees, but the integrated value is 45 degrees.

**Comment by fary99** [comment]
您好！ICM42688-P的陀螺仪默认精度为±2000bps,这里类比到16位数即范围（-2000——2000）相当于（0——65535）。
不知道这样的解答有没有解决您的问题，期待着你的回复
